### ISSUE TITLE
High DPI Support?

### ISSUE THREAD

**Issue by samwalls** [gamax92/OCEmu#22]
When using the emulator on my machine which has a high-dpi screen, it's really difficult to read the text. Is there a way of configuring the emulator for different screen sizes currently?
If not, SDL apparently has a [windowing flag](https://wiki.libsdl.org/SDL_WindowFlags) called `SDL_WINDOW_ALLOW_HIGHDPI` maybe enabling this would help - however I think it has to be called when the window is created and an openGL context is attached (might not be accessible through the lua binding, but you know better than me).

Here's a picture for context ;)

![screen5](https://cloud.githubusercontent.com/assets/2551718/21285165/35c9f7d8-c429-11e6-90bc-82c9206f9e1d.png)

**Comment by gamax92** [comment]
Ahh thank you for reporting this, the SDL2 binding I uses is just a raw ffi binding to SDL2 so everything is accessable, though it currently doesn't know about the SDL_WINDOW_ALLOW_HIGHDPI flag

I'll go add that in and add the flag.

**Comment by gamax92** [comment]
the SDL2 window is now being created with SDL_WINDOW_ALLOW_HIGHDPI, can you check and see if it's working properly now?

EDIT: I'm being told this won't matter on anything that isn't macOS, as the Windows and Linux backends don't support the HIGHDPI flag, and rely on the OS to scale the window up.

**Comment by gamax92** [comment]
Until SDL2 gets proper highdpi support or Linux gets better low dpi window support, the best I can offer for now is a --highdpi flag you can pass to OCEmu

**Comment by samwalls** [comment]
Thank's for looking into it - it was kind of looking bleak for high-dpi support anyway. I'll test it out when I get a chance.

**Comment by gamax92** [comment]
Report back on this? how does the function work for you?

**Comment by samwalls** [comment]
I was a bit of a bad person and forgot about this completely ;)

Anyway, for my configuration at least, you can consider it fixed!

![ocemu](https://cloud.githubusercontent.com/assets/2551718/22770603/9710d4be-ee89-11e6-98d9-1bcef27a4736.png)

The computer on the right was opened with `--highdpi`
