### ISSUE TITLE
Networking Separate Emulator Instances

### ISSUE THREAD

**Issue by samwalls** [gamax92/OCEmu#23]
Is it currently possible to link emulator instances, such that I can test my modem code between them?

If this is the case I would love to know how, this would save a lot of time faffing around in actual minecraft ;) - otherwise take this as a feature suggestion.

**Comment by TGRHavoc** [comment]
@samwalls I don't know if you have figured this out yet but, you can network two separate instances of the emulator. If not, just follow the instructions 😄 

1. Start a new instance (e.g `ocmue.exe %appdata%/ocemu/computer_2`) then exit it
2. ~~Configure new instance~~
    - ~~Edit the `ocemu.cfg` file changing the emulator settings (http://i.imgur.com/FL8Xhly.png) changing the addresses for the components (there's probably an easier way of doing this)~~
3. Start the new instance and write your modem code 😃 

Image of networking working:

![Modem working](http://i.imgur.com/vMQZzhk.png)


~~If you don't change the addresses, you'll probably end up with the following message in console:
![Address clash](http://i.imgur.com/ELHhGYc.png)~~
