### ISSUE TITLE
OCEmu.exe doesn't pass any arguments

### ISSUE THREAD

**Issue by kitsu** [gamax92/OCEmu#26]
Just downloaded latest Windows binaries.
After messing around getting just OCEmu.exe on my path I tried calling it with the path to my HDD from my current world, but no matter what I tried it just boots the default image.

I did some print-debugging in `boot.lua` and found that my arguments aren't passed to the script.

Here is my `OCEmu.cmd` file located at `c:\bin`:

``` batch
@echo off
pushd .
echo %~f1
cd /D C:\bin\OCEmu-x32\
OCEmu.exe "%~f1"
popd
```

I tried running the exe directly with the same result.

**Comment by gamax92** [comment]
Apologies for the delay, issue should be fixed in 1419e19f58a3f16aa611f9313ed401153deca352

Both 32bit and 64bit zip archives have been updated.
