### ISSUE TITLE
boot.lua don't start

### ISSUE THREAD

**Issue by AR2000AR** [gamax92/OCEmu#37]
```
~/OCEmu/OCEmu-master/src $ lua boot.lua
Illegal instruction
```
I can't start the boot.lua

**Comment by comfix** [comment]
I tried it myself about an hour ago and I just got an segmentation fault.

**Comment by gamax92** [comment]
I don't know what to tell you, are you trying to use a lua binary that isn't compiled for a raspberry pi?
Maybe you've compiled some of the lua libraries wrong, I don't know.
OCEmu has never been tested on an arm device before so no idea what to tell you.

Either way this is not an OCEmu issue.

**Comment by AR2000AR** [comment]
Almost all lua libraries have been download from the package manager. Only luautf8 and luaffi have been downloaded whith luarock
