### ISSUE TITLE
HTTP request failed: unsupported protocol

### ISSUE THREAD

**Issue by polyzium** [gamax92/OCEmu#39]
Happens when i try to run `pastebin` or `wget`.
![image](https://user-images.githubusercontent.com/22579935/27987883-1f3b950e-641e-11e7-804c-c4a81c5ee7f4.png)

**Comment by gamax92** [comment]
It seems you do not have luasec installed, OCEmu needs this for https support.

**Comment by polyzium** [comment]
My bad... I am confused because I have lua 5.3 and lua 5.2 both installed and looks like I installed luasec for lua 5.3... now I feel stupid.

Closing
