### ISSUE TITLE
Missing lua module

### ISSUE THREAD

**Issue by kevinkk525** [gamax92/OCEmu#44]
When trying to start "lua boot.lua" I got the error message that module "ffi" was missing.
Executing "luarocks install --server=http://luarocks.org/dev luaffi" fixed that and the emulator started correctly. 
thanks a lot.

**Comment by gamax92** [comment]
If you're able to use the version from luarocks, then great. However luaffifb is incompatible with GCC 7 in it's present state, hence why I no longer use the version from luarocks and instead a patched version included as a submodule.

If the luaffifb folder is blank for you, please either clone with submodules: `git clone --recursive`
Or initialize submodules later: `git submodule update --init --recursive`
